import type { Metadata } from "next";
import { Fira_Sans } from "next/font/google";
import "./globals.scss";
import InfoNavbar from "@/Components/InfoNavbar";
import Navbar from "@/Components/Navbar";
import FooterNav from "@/Components/FooterNav";

const fira = Fira_Sans({
  subsets: ['latin'],
  weight: ['100','200','300','400','500','600','700','800','900']
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={fira.className}>
        <InfoNavbar />
        <Navbar />
        <FooterNav />
        {children}
      </body>
    </html>
  );
}
